### ISSUE TITLE
Converting ember-api-docs to typescript

### ISSUE THREAD

**Issue by dwickern** [typed-ember/ember-cli-typescript#68]
I wanted to check the progress of all the work we've been doing, so I decided to convert an open source ember app to typescript and document the results.

First I tried converting the travis-ci app, but they're doing non-compliant decorator things. I settled on ember-api-docs: a small but non-trivial app that shows up on a google search for "ember app list".

All I've done is install e-c-ts and rename `.js` to `.ts`. I'm building against my local custom build of ember-typings which has some outstanding PRs merged.

It went surprisingly well! I went through the error log and categorized the errors. We already know about many of these problems and there are some new ones. I'll open new issues for some of them.

---

1.

> app/initializers/scroll-parent-shim.ts(1,8): error TS1192: Module ''jquery'' has no default export.
> app/mixins/scroll-tracker.ts(3,8): error TS1192: Module ''jquery'' has no default export.

```ts
import $ from 'jquery';
```

Is this a shim for `window.jQuery`? Who exports it?

---

2.

> app/initializers/scroll-parent-shim.ts(5,14): error TS2304: Cannot find name 'FastBoot'.
app/mixins/scroll-tracker.ts(17,19): error TS2304: Cannot find name 'FastBoot'.

```ts
if (typeof FastBoot !== 'undefined') {
  return
}
```

Missing typings for fastboot

---
  
3.

> app/mixins/scroll-tracker.ts(21,20): error TS2339: Property 'APP' does not exist on type 'typeof config'.
> ember-api-docs/adapters/application.ts(11,13): error TS2339: Property 'API_HOST' does not exist on type 'typeof config'.
> ember-api-docs/router.ts(11,19): error TS2339: Property 'routerRootURL' does not exist on type 'typeof config'.

```ts
import config from 'ember-api-docs/config/environment';

$(config.APP.scrollContainerSelector).scrollTop(offset - 10);
```

It's not possible to define the environment config in typescript. Work around by adding to `app/config/environment.d.ts`

---

4.

> app/utils/get-last-version.ts(1,27): error TS2307: Cannot find module 'npm:semver-compare'.
> ember-api-docs/components/api-index-filter.ts(3,18): error TS2307: Cannot find module 'npm:lodash.uniq'.
> ember-api-docs/components/api-index-filter.ts(4,20): error TS2307: Cannot find module 'npm:lodash.sortby'.

```ts
import semverCompare from 'npm:semver-compare';
```

Missing typings for `ember-browserify`

---

5.

> app/utils/request-idle-callback.ts(1,8): error TS1192: Module '"/users/dwickern/code/ember-api-docs/node_modules/@types/rsvp/index"' has no default export.
> ember-api-docs/components/search-input.ts(2,10): error TS2305: Module '"/users/dwickern/code/ember-typings/node_modules/@types/rsvp/index"' has no exported member 'denodeify'.
> ember-api-docs/routes/class.ts(1,10): error TS2305: Module '"/users/dwickern/code/ember-typings/node_modules/@types/rsvp/index"' has no exported member 'hash'.
> ember-api-docs/routes/class.ts(1,16): error TS2305: Module '"/users/dwickern/code/ember-typings/node_modules/@types/rsvp/index"' has no exported member 'resolve'.

```ts
import RSVP from 'rsvp';
import { hash, resolve } from 'rsvp';
```

The RSVP typings only declare typings for `require('rsvp')`. Is this "rsvp" module actually a shim added by ember?

---

6.

> app/utils/request-idle-callback.ts(8,12): error TS2555: Expected at least 3 arguments, but got 2.

```ts
import { run } from '@ember/runloop';
return run.scheduleOnce('afterRender', cb);
```

Incomplete typings for `scheduleOnce`

---

7.

> ember-api-docs/tests/acceptance/analytics-page-tracking-test.ts(13,33): error TS2339: Property 'application' does not exist on type 'TestContext'.

```ts
test('checking that trackPage gets called on transitions', async function(assert) {
  const analyticsService = this.application.__container__.lookup('service:analytics');
})
```

The `application` property is added by a custom test helper `module-for-acceptance`. You can fix this error with a merged declaration.

```ts
// tests/helpers/module-for-acceptance.ts
import Application from '@ember/application';

declare module "qunit" {
  interface TestContext {
    application: Ember.Application;
  }
}
```
(you'll now have an error on `__container__` though because there aren't typings for it, but that's a separate problem)

I think this `module-for-acceptance` is a blueprint added to all projects by default? Maybe we should have an updated blueprint to fix this common issue.

---

8.

> ember-api-docs/tests/acceptance/analytics-page-tracking-test.ts(29,29): error TS2345: Argument of type '2000' is not assignable to parameter of type '{ timeout: any; }'.

```ts
export function requestIdlePromise({timeout}) {
  ...
}
return requestIdlePromise(2000);
```

Typescript caught a bug! :tada:

---

9.

> ember-api-docs/tests/acceptance/app-layout-test.ts(10,9): error TS2304: Cannot find name 'selectSearch'.
> ember-api-docs/tests/acceptance/switch-versions-test.ts(14,9): error TS2304: Cannot find name 'selectChoose'.

```ts
await selectSearch('.select-container', '2');
```

Missing typings for `ember-power-select`

---

10.

> ember-api-docs/tests/helpers/resolver.ts(1,22): error TS2307: Cannot find module '../../resolver'.
> ember-api-docs/tests/helpers/start-app.ts(3,25): error TS2307: Cannot find module '../../app'.
> ember-api-docs/tests/helpers/start-app.ts(4,20): error TS2307: Cannot find module '../../config/environment'.

```ts
import Resolver from '../../resolver';
import config from '../../config/environment';
import Application from '../../app';
```

At least I'm not the only one confused by this.

---

11.

> ember-api-docs/tests/test-helper.ts(3,27): error TS2307: Cannot find module 'ember-exam/test-support/load'.

```ts
import loadEmberExam from 'ember-exam/test-support/load';
loadEmberExam();
```

Missing typings for `ember-exam`

---

12.

> ember-api-docs/tests/unit/initializers/scroll-parent-shim-test.ts(21,3): error TS2554: Expected 0 arguments, but got 1.

```ts
import { initialize } from 'ember-api-docs/initializers/scroll-parent-shim';
initialize(this.application);

export function initialize() {
}
```

Good.

---

13.

> ember-api-docs/adapters/application.ts(3,19): error TS2307: Cannot find module 'fetch'.

```ts
import fetch from 'fetch';
```

ember-cli/ember-fetch#72

---

14.

> ember-api-docs/components/ember-anchor.ts(3,29): error TS2307: Cannot find module 'ember-anchor/components/ember-anchor'.
> ember-api-docs/controllers/events.ts(3,37): error TS2307: Cannot find module 'ember-anchor/mixins/controller-support'.

```ts
import AnchorComponent from 'ember-anchor/components/ember-anchor';
```

Missing typings for `ember-anchor`

---

15.

> ember-api-docs/components/search-input.ts(7,17): error TS2307: Cannot find module 'ember-metal/get'.
> ember-api-docs/components/search-input.ts(8,17): error TS2307: Cannot find module 'ember-metal/set'.

```ts
import get from 'ember-metal/get';
import set from 'ember-metal/set';
```

Missing typings for `ember-metal`. Is this public API?

---

16.

> ember-api-docs/components/search-input/dropdown.ts(28,20): error TS2345: Argument of type '"results.length"' is not assignable to parameter of type 'never'.
> ember-api-docs/components/ember-anchor.ts(11,36): error TS2345: Argument of type '"attrs.a"' is not assignable to parameter of type 'never'.
> ember-api-docs/components/search-input/dropdown.ts(28,20): error TS2345: Argument of type '"results.length"' is not assignable to parameter of type 'never'.
> ember-api-docs/components/search-input/dropdown.ts(55,41): error TS2345: Argument of type '"hierarchy.lvl1"' is not assignable to parameter of type 'never'.

```ts
if (!get(this, 'results.length')) {
  return {};
}
let filterValue = get(this, `filterData.show${capitalize(filter)}`) ? filter : null;
let lvl0 = capitalize(get(current, 'hierarchy.lvl0'));
```

Ember typings don't support paths

---

17.

> ember-api-docs/controllers/project-version.ts(53,37): error TS2339: Property 'sort' does not exist on type 'NativeArray<{}>'.
> ember-api-docs/mixins/filter-params.ts(22,19): error TS2339: Property 'push' does not exist on type 'NativeArray<{}>'.
> ember-api-docs/mixins/filter-params.ts(35,33): error TS2339: Property 'includes' does not exist on type 'NativeArray<{}>'.

```ts
let filters = A(value.split(','));
let enabled = filters.includes(filter);
```

This seems to be a bug in ember typings.

---

18.

> ember-api-docs/models/missing.ts(1,19): error TS2307: Cannot find module 'ember-data/model'.

```ts
import Model from 'ember-data/model';
```

Missing typings for ember-data shims

---

19.

> ember-api-docs/router.ts(22,11): error TS2339: Property 'map' does not exist on type 'Readonly<typeof Router> & (new () => { analytics: ComputedProperty<Service>; location: string; ro...'.

```ts
const AppRouter = Router.extend({
  ...
});

AppRouter.map(function() {
  this.route('404');
  ...
});
```

Incomplete typings for `Ember.Router`

---

20.

> ember-api-docs/services/analytics.ts(21,5): error TS1320: Type of 'await' operand must either be a valid promise or must not contain a callable 'then' member.

```ts
await requestIdlePromise({timeout: 1000});

export function requestIdlePromise({timeout}) {
  return new RSVP.Promise(resolve => {
    requestIdleCb(resolve, {timeout});
  });
}
```

Incomplete typings for `RSVP`

---

- [ ] 1. typings for jquery shim - typed-ember/ember-cli-typescript#71
- [ ] 2. typings for fastboot
- [x] 3. typings for config/environment.ts
- [ ] 4. typings for ember-browserify
- [ ] 5. rsvp module imports - typed-ember/ember-cli-typescript#71
- [x] 6. typings for scheduleOnce - typed-ember/ember-typings#50
- [ ] 7. typings for module-for-acceptance
- [x] 8. N/A - bug in application
- [ ] 9. typings for ember-power-select
- [ ] 10. typings for relative test imports
- [ ] 11. typings for ember-exam
- [x] 12. N/A - bug in application
- [ ] 13. typings for ember-fetch - ember-cli/ember-fetch#72
- [ ] 14. typings for ember-anchor
- [ ] 15. typings for ember-metal
- [x] 16. typings for unsafe paths - typed-ember/ember-typings#51
- [x] 17. typings for NativeArray - typed-ember/ember-typings#49
- [x] 18. typings for ember-data shims - https://github.com/typed-ember/ember-data-shim-typings
- [x] 19. typings for Router.map - typed-ember/ember-typings#46
- [x] 20. typings for rsvp - typed-ember/ember-typings#42

**Comment by chriskrycho** [comment]
1. `$`: Ember itself exports it, [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/jquery.js)

**Comment by locks** [comment]
18. Also old shims, should be avoided.

**Comment by dwickern** [comment]
1. jQuery uses `export =` instead of `export default` in their typings. I think this can be fixed using the `allowSyntheticDefaultImports` compiler option

**Comment by dwickern** [comment]
To follow up, we've fixed several of the original issues. Most of the remaining issues are missing typings for ember addons. I put together a checkbox list at the bottom of my original post.

I had another look at the app. There are some cases where the typings don't work. I think the majority of the app code is inferring `any` and is basically still javascript.

Here's one instance where I tried to add typings:
```ts
// app/controllers/project-version.ts
import ProjectVersion from '../models/project-version';

export default Controller.extend(FilterParams, {
  model: null as ProjectVersion, // <- added this line

  getRelationshipIDs(relationship: string) {
    // even with the explicit type above, `model` is inferred as `any`
    const classes = this.get('model').hasMany(relationship);

    const sorted = A(classes.ids()).sort();
    return A(sorted).toArray().map(id => id.split('-').pop());
  },
}
```
This sort of self-referential typing only works in ES6 classes, so to to get the most out of TS you do need to use them. We would really benefit from an automated conversion, especially if it works on typescript code

**Comment by chriskrycho** [comment]
- Re: config/environment—we have a stub we're already generating, and I think we can and should continue to generate that. It could also use documentation about the best way to handle that. (Ultimately, I'd love for config/environment to be able to *be* TS, but I haven't thought through that all the way yet, and I'm not sure it's worth it given some of the tradeoffs Rob mentioned around some of the build config stuff a while back.)
- Re: ember-metal—as noted up-thread, we can say "We're not typing `"ember-metal"`; upgrade to use the imports from `"@ember/object"` instead.
- module-for-acceptance—I have typings locally for this in my own app, which we should be able to upstream easily enough
- ember-power-select—most likely just blocked on us shipping the addon-supporting release of this; Miguel has mentioned he actively *wants* to integrate TS into his addons.

The big pain point I have *no* idea how to tackle is things exposed by ember-browserify. That's a really weird pattern to me *anyway*; that goes double when trying to map it over to TS modules.

**Comment by dwickern** [comment]
Right, the ENV typings take us into build-time typings for node, broccoli, ember-cli-build, etc. That would be really nice but it's a long way off. We're doing the best we can right now.

Re: shims, I would still like to have these if it will help with typescript adoption. It seems like the E-D shims are still frequently used. Maybe we can offer these in a separate typings package.

Re: browserify, I think each individual app will need their own shims, for example
```ts
declare module 'npm:semver-compare' {
  import SemverCompare = require("semver-compare"); // from @types/semver-compare
  export default SemverCompare;
}
```
Or to silence the errors you can do something like this
```ts
declare module 'npm:*' {
  export default typeof any;
}
```

**Comment by chriskrycho** [comment]
I'd definitely be better with the ember-data shims that the regular Ember module shims, since there's a straightforward way to handle the latter.

I think you're right about the npm bits – best we can do there is probably document it.

**Comment by dwickern** [comment]
I'll need the ember-data shims for my own app either way. My generator blueprints still use shim imports (I'm on E-D 2.6.1)

**Comment by chriskrycho** [comment]
@dwickern I'm going to go ahead and close this, since we're no longer pursuing this particular course of evaluation. (Feel free to reopen if you think we should.)
